### ISSUE TITLE
How to get library

### ISSUE THREAD

**Issue by phantuanphong** [aradomski/Navigator#1]
How to get library?

**Comment by aradomski** [comment]
A the moment I've got only one way to get the library.
You must download the code and attach it to your project in similar way as it is done in app module. (see 
https://github.com/aradomski/Navigator/blob/master/app/build.gradle file)
crucial lines:

```
apply plugin: 'com.neenbedankt.android-apt'

compile project(':navigator')
apt project(':compiler')
```

Library depends on android-apt 1.5 version so you need to include this either. (see  https://github.com/aradomski/Navigator/blob/master/build.gradle) 

Crucial line:

```
 classpath 'com.neenbedankt.gradle.plugins:android-apt:1.5'
```

**Comment by aradomski** [comment]
I've updated android-apt to 1.7 version. Now including library should look like this:
https://github.com/aradomski/Navigator/blob/master/app/build.gradle file

crucial lines:

```
apply plugin: 'com.neenbedankt.android-apt'
compile project(':compiler')
apt {
  processor "pl.edu.radomski.navigator.NavigatorAnnotationProcessor"
}
```

https://github.com/aradomski/Navigator/blob/master/build.gradle

```
classpath 'com.neenbedankt.gradle.plugins:android-apt:1.7'
```

**Comment by phantuanphong** [comment]
Thanks you
